name: Build theme

on: [push]

jobs:
  build-theme:
    runs-on: ubuntu-latest
    name: Build theme package
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Build and package
        id: build_and_package
        run: |
          npm install
          npm run pretest
          npm run test
          npm run package
          echo "asset_name=$(ls -1 jsonresume-theme-helloquan-*.tgz)" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: theme-artifacts
          path: ${{ steps.build_and_package.outputs.asset_name }}

      - name: Prepare public directory
        run: |
          mkdir public
          cp test/resume.html public/index.html

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-theme:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build-theme
    runs-on: ubuntu-latest
    name: Release and publish theme
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: theme-artifacts

      - name: Get asset name
        id: get_asset_name
        run: echo "asset_name=$(ls -1 jsonresume-theme-helloquan-*.tgz)" >> $GITHUB_OUTPUT

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.get_asset_name.outputs.asset_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
